name: gitStream
'on':
  - pull_request
jobs:
  gitstream:
    runs-on: ubuntu-latest
    outputs:
      lane_bug_fix_active: ${{ steps.checks.outputs.lane_bug_fix_active }}
      gate_small_passed: ${{ steps.checks.outputs.gate_small_passed }}
      gate_add_tests_passed: ${{ steps.checks.outputs.gate_add_tests_passed }}
      gate_docs_update_passed: ${{ steps.checks.outputs.gate_docs_update_passed }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          path: code
      - name: Checkout default branch to process the repo .cm file
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.repository.default_branch }}
          path: cm
      - name: Run gitstream checks
        uses: linear-b/actions/gitstream@v2
        id: checks
        with:
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref }}
          base: ${{ github.base_ref }}
          use_cache: false
          source_path: code
          cm_path: cm
  lane_bug_fix:
    needs: gitstream
    if: needs.gitstream.outputs.lane_bug_fix_active == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: bug
          token: ${{ secrets.GITHUB_TOKEN }}
  gate_small:
    needs: gitstream
    if: needs.gitstream.outputs.gate_small_passed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: small
  gate_add_tests:
    needs: gitstream
    if: needs.gitstream.outputs.gate_add_tests_passed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: add_tests
          token: ${{ secrets.GITHUB_TOKEN }}
  gate_docs_update:
    needs: gitstream
    if: needs.gitstream.outputs.gate_docs_update_passed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: docs
          token: ${{ secrets.GITHUB_TOKEN }}
