name: Gitstream action, executes repo rule based on repo's gitstream.yml
'on':
  - pull_request
jobs:
  gitstream:
    runs-on: ubuntu-latest
    outputs:
      add_tests_passed: ${{ steps.checks.outputs.add_tests_passed }}
      add_tests_active: ${{ steps.checks.outputs.add_tests_active }}
      small_passed: ${{ steps.checks.outputs.small_passed }}
      small_active: ${{ steps.checks.outputs.small_active }}
      docs_update_passed: ${{ steps.checks.outputs.docs_update_passed }}
      docs_update_active: ${{ steps.checks.outputs.docs_update_active }}
    steps:
      - run: echo "getting the repo code"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run gitstream checks
        uses: vim-zz/action1@v1
        id: checks
        with:
          lanes: add_tests,small,docs_update,
  add_tests:
    needs: gitstream
    if: >-
      needs.gitstream.outputs.add_tests_passed == 'true' &&
      needs.gitstream.outputs.add_tests_active == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - run: echo "PASSED ${{ needs.gitstream.outputs.add_tests_passed }}"
      - run: echo "ACTIVE ${{ needs.gitstream.outputs.add_tests_active }}"
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "PASSED ${{ needs.gitstream.outputs.add_tests_passed }}"
      - run: echo "ACTIVE ${{ needs.gitstream.outputs.add_tests_active }}"
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: add_tests
          token: ${{ secrets.GITHUB_TOKEN }}
  small:
    needs: gitstream
    if: >-
      needs.gitstream.outputs.small_passed == 'true' &&
      needs.gitstream.outputs.small_active == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - run: echo "PASSED ${{ needs.gitstream.outputs.small_passed }}"
      - run: echo "ACTIVE ${{ needs.gitstream.outputs.small_active }}"
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: xsmall
  docs_update:
    needs: gitstream
    if: >-
      needs.gitstream.outputs.docs_update_passed == 'true' &&
      needs.gitstream.outputs.docs_update_active == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - run: echo "PASSED ${{ needs.gitstream.outputs.docs_update_passed }}"
      - run: echo "ACTIVE ${{ needs.gitstream.outputs.docs_update_active }}"
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "PASSED ${{ needs.gitstream.outputs.docs_update_passed }}"
      - run: echo "ACTIVE ${{ needs.gitstream.outputs.docs_update_active }}"
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: add_tests
          token: ${{ secrets.GITHUB_TOKEN }}
