name: gitStream
'on':
  - pull_request
jobs:
  gitstream:
    runs-on: ubuntu-latest
    outputs:
      lane_add_tests_active: ${{ steps.checks.outputs.lane_add_tests_active }}
      lane_docs_update_active: ${{ steps.checks.outputs.lane_docs_update_active }}
      gate_small_passed: ${{ steps.checks.outputs.gate_small_passed }}
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          path: code
      - name: Checkout base branch to compare with
        uses: actions/checkout@v3
        with:
          ref: ${{ github.base_ref }}
          path: base
      - name: Checkout default branch to process the repo .cm file
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.repository.default_branch }}
          path: cm
      - name: Run gitstream checks
        uses: linear-b/actions/gitstream@v2
        id: checks
        with:
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref }}
          base: ${{ github.base_ref }}
          use_cache: false
          source_path: code
          cm_path: cm
          base_path: base
  lane_add_tests:
    needs: gitstream
    if: needs.gitstream.outputs.lane_add_tests_active == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: tests
  lane_docs_update:
    needs: gitstream
    if: needs.gitstream.outputs.lane_docs_update_active == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: docs
  gate_small:
    needs: gitstream
    if: needs.gitstream.outputs.gate_small_passed == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: small
