name: Gitstream action, executes repo rule based on repo's gitstream.yml
'on':
  - pull_request
jobs:
  gitstream:
    runs-on: ubuntu-latest
    outputs:
      assets_change_passed: ${{ steps.checks.outputs.assets_change_passed }}
      assets_change_active: ${{ steps.checks.outputs.assets_change_active }}
      docs_change_passed: ${{ steps.checks.outputs.docs_change_passed }}
      docs_change_active: ${{ steps.checks.outputs.docs_change_active }}
    steps:
      - run: echo "getting the repo code"
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Run gitstream checks
        uses: vim-zz/action1@v1
        id: checks
        with:
          lanes: assets_change,docs_change,
  assets_change:
    needs: gitstream
    if: >-
      needs.gitstream.outputs.assets_change_passed == 'true' &&
      needs.gitstream.outputs.assets_change_active == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - run: echo "PASSED ${{ needs.gitstream.outputs.assets_change_passed }}"
      - run: echo "ACTIVE ${{ needs.gitstream.outputs.assets_change_active }}"
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: assets_change
          token: ${{ secrets.GITHUB_TOKEN }}
  docs_change:
    needs: gitstream
    if: >-
      needs.gitstream.outputs.docs_change_passed == 'true' &&
      needs.gitstream.outputs.docs_change_active == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - run: echo "PASSED ${{ needs.gitstream.outputs.docs_change_passed }}"
      - run: echo "ACTIVE ${{ needs.gitstream.outputs.docs_change_active }}"
      - uses: juliangruber/approve-pull-request-action@v1.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: 1
      - run: echo "PASSED ${{ needs.gitstream.outputs.docs_change_passed }}"
      - run: echo "ACTIVE ${{ needs.gitstream.outputs.docs_change_active }}"
      - uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: autoapproved
